<?php
$catalogSearchHelper =  $this->helper('catalogsearch');
$catalogSearchHelper->getEscapedQueryText();
$url = $catalogSearchHelper->getResultUrl($catalogSearchHelper->getEscapedQueryText());
$_productCollection = $this->getProductCollection();

$_productCount = count($_productCollection);
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>

<ul class="products-list">
    <li id="autocomplete_hidden" class="autocomplete_hidden"><span style="text-align:center;"></li>
    <?php if($_productCount == 0): ?>
        <li class="notice-message"><?php echo Mage::helper('autocomplete')->getNoticeMessage(); ?></li>
    <?php endif; ?>
    <?php $counter = 0;foreach ($_productCollection as $_product): ?>
        <li class="<?php echo (++$counter + 1)%2?'odd':'even'?><?php if($counter==1){ echo ' first';}elseif($counter==$_productCount){ echo ' last';}  ?>">
            <a href="<?php echo $_product['productUrl']; ?>" style="text-decoration:none;">
                <div class="img-box-area">
                    <img src="<?php echo $_product['productThumbnailUrl']; ?>" width="80" height="80" alt="<?php echo $_product['name'] ?>"/>
                </div>
                <div class="content-box-area" style="text-align: left ! important; font-size: 12px ! important;margin-left:80px !important;margin-right:5px !important;">
                    <h3 style="text-align: left ! important; font-size: 12px ! important;"><?php echo $_product['name']; ?></h3>
                    <span><?php echo $_product['decriptionHTML']; ?> ...</span>
                    <div class="auto-fright" style="">
                        <span><?php echo 'Price '.$_product['priceHTML'] ?></span>
                    </div>
                </div>
                <div class="clear"></div>
            </a>
        </li>
    <?php endforeach; ?>
    <?php //exit; ?>
</ul>
<?php  if($_productCount): ?>
    <div align="center"><a href="<?php echo $url ?>">View All</a></div>
<?php endif; ?>
